// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentLifeApp_BE.Models;

#nullable disable

namespace StudentLifeApp_BE.Migrations
{
    [DbContext(typeof(LmsDbContext))]
    partial class LmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentLifeApp_BE.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AssignmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime");

                    b.Property<double>("MaxScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(10.0);

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("AssignmentId")
                        .HasName("PK__Assignme__32499E57FC1C1C0A");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("SubjectId");

                    b.ToTable("Assignments");

                    b.HasData(
                        new
                        {
                            AssignmentId = 1,
                            CreatedBy = 2,
                            Deadline = new DateTime(2026, 3, 11, 23, 59, 0, 0, DateTimeKind.Utc),
                            MaxScore = 10.0,
                            SubjectId = 1,
                            Title = "Math Homework 1",
                            Weight = 0.20000000000000001
                        },
                        new
                        {
                            AssignmentId = 2,
                            CreatedBy = 2,
                            Deadline = new DateTime(2026, 3, 18, 23, 59, 0, 0, DateTimeKind.Utc),
                            MaxScore = 10.0,
                            SubjectId = 1,
                            Title = "Math Homework 2",
                            Weight = 0.20000000000000001
                        },
                        new
                        {
                            AssignmentId = 3,
                            CreatedBy = 2,
                            Deadline = new DateTime(2026, 3, 14, 23, 59, 0, 0, DateTimeKind.Utc),
                            MaxScore = 15.0,
                            SubjectId = 2,
                            Title = "Physics Lab Report",
                            Weight = 0.29999999999999999
                        },
                        new
                        {
                            AssignmentId = 4,
                            CreatedBy = 2,
                            Deadline = new DateTime(2026, 3, 21, 23, 59, 0, 0, DateTimeKind.Utc),
                            MaxScore = 15.0,
                            SubjectId = 2,
                            Title = "Physics Experiment",
                            Weight = 0.29999999999999999
                        },
                        new
                        {
                            AssignmentId = 5,
                            CreatedBy = 2,
                            Deadline = new DateTime(2026, 3, 9, 23, 59, 0, 0, DateTimeKind.Utc),
                            MaxScore = 20.0,
                            SubjectId = 3,
                            Title = "English Essay",
                            Weight = 0.5
                        },
                        new
                        {
                            AssignmentId = 6,
                            CreatedBy = 2,
                            Deadline = new DateTime(2026, 3, 17, 23, 59, 0, 0, DateTimeKind.Utc),
                            MaxScore = 12.0,
                            SubjectId = 4,
                            Title = "Chemistry Lab",
                            Weight = 0.25
                        });
                });

            modelBuilder.Entity("StudentLifeApp_BE.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EnrollmentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<bool>("IsTeacher")
                        .HasColumnType("bit");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("SubjectID");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("EnrollmentId")
                        .HasName("PK__Enrollme__7F6877FB6B53A844");

                    b.HasIndex("SubjectId");

                    b.HasIndex(new[] { "UserId", "SubjectId" }, "UQ_Enrollment")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            EnrollmentId = 1,
                            IsTeacher = true,
                            SubjectId = 1,
                            UserId = 2
                        },
                        new
                        {
                            EnrollmentId = 2,
                            IsTeacher = true,
                            SubjectId = 2,
                            UserId = 2
                        },
                        new
                        {
                            EnrollmentId = 3,
                            IsTeacher = true,
                            SubjectId = 3,
                            UserId = 2
                        },
                        new
                        {
                            EnrollmentId = 4,
                            IsTeacher = true,
                            SubjectId = 4,
                            UserId = 2
                        },
                        new
                        {
                            EnrollmentId = 5,
                            IsTeacher = false,
                            SubjectId = 1,
                            UserId = 3
                        },
                        new
                        {
                            EnrollmentId = 6,
                            IsTeacher = false,
                            SubjectId = 2,
                            UserId = 3
                        },
                        new
                        {
                            EnrollmentId = 7,
                            IsTeacher = false,
                            SubjectId = 1,
                            UserId = 4
                        },
                        new
                        {
                            EnrollmentId = 8,
                            IsTeacher = false,
                            SubjectId = 3,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("StudentLifeApp_BE.Models.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NewsID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("TargetRoleId")
                        .HasColumnType("int")
                        .HasColumnName("TargetRoleID");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("NewsId")
                        .HasName("PK__News__954EBDD396EF45C1");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TargetRoleId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            NewsId = 1,
                            Content = "This is a seeded announcement for all users. Welcome to our Learning Management System!",
                            CreatedAt = new DateTime(2026, 3, 4, 8, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            IsActive = true,
                            Title = "Welcome to LMS"
                        },
                        new
                        {
                            NewsId = 2,
                            Content = "System maintenance will occur on March 5th, 2026 from 2 AM to 4 AM UTC.",
                            CreatedAt = new DateTime(2026, 3, 4, 9, 30, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            IsActive = true,
                            Title = "System Maintenance"
                        },
                        new
                        {
                            NewsId = 3,
                            Content = "Please note that all assignments must be submitted before the deadline.",
                            CreatedAt = new DateTime(2026, 3, 4, 10, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 2,
                            IsActive = true,
                            TargetRoleId = 3,
                            Title = "Assignment Deadline Reminder"
                        });
                });

            modelBuilder.Entity("StudentLifeApp_BE.Models.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NoteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoteId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("NoteId")
                        .HasName("PK__Notes__EACE357F98EE0990");

                    b.HasIndex("UserId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            NoteId = 1,
                            Content = "Study at least 1 hour/day for mathematics. Focus on algebra and geometry.",
                            CreatedAt = new DateTime(2026, 3, 4, 8, 0, 0, 0, DateTimeKind.Utc),
                            IsPinned = true,
                            Title = "Study Plan",
                            UserId = 3
                        },
                        new
                        {
                            NoteId = 2,
                            Content = "Review Newton's laws and kinematics before the next class.",
                            CreatedAt = new DateTime(2026, 3, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            IsPinned = false,
                            Title = "Physics Notes",
                            UserId = 3
                        },
                        new
                        {
                            NoteId = 3,
                            Content = "Learn 10 new vocabulary words every day for the essay assignment.",
                            CreatedAt = new DateTime(2026, 3, 4, 14, 0, 0, 0, DateTimeKind.Utc),
                            IsPinned = false,
                            Title = "English Vocabulary",
                            UserId = 4
                        },
                        new
                        {
                            NoteId = 4,
                            Content = "Prepare lab equipment and read the experiment procedure carefully.",
                            CreatedAt = new DateTime(2026, 3, 4, 15, 30, 0, 0, DateTimeKind.Utc),
                            IsPinned = true,
                            Title = "Chemistry Lab Preparation",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("StudentLifeApp_BE.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3ABF28B166");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B6160D9F003C9")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Teacher"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Student"
                        });
                });

            modelBuilder.Entity("StudentLifeApp_BE.Models.StudentAssignmentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("AssignmentID");

                    b.Property<double?>("Score")
                        .HasColumnType("float");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__StudentA__3214EC2749C02C47");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "AssignmentId", "StudentId" }, "UQ_Student_Assignment")
                        .IsUnique();

                    b.ToTable("StudentAssignmentStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignmentId = 1,
                            Score = 9.0,
                            StudentId = 3,
                            SubmittedAt = new DateTime(2026, 3, 3, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AssignmentId = 1,
                            Score = 8.5,
                            StudentId = 4,
                            SubmittedAt = new DateTime(2026, 3, 3, 14, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AssignmentId = 3,
                            Score = 13.0,
                            StudentId = 3,
                            SubmittedAt = new DateTime(2026, 3, 2, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AssignmentId = 5,
                            Score = 18.0,
                            StudentId = 4,
                            SubmittedAt = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AssignmentId = 6,
                            Score = 11.0,
                            StudentId = 5,
                            SubmittedAt = new DateTime(2026, 3, 4, 11, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("StudentLifeApp_BE.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubjectID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SubjectId")
                        .HasName("PK__Subjects__AC1BA3880C5F783A");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            SubjectId = 1,
                            Credits = 3,
                            Description = "Basic mathematics and algebra",
                            SubjectName = "Mathematics"
                        },
                        new
                        {
                            SubjectId = 2,
                            Credits = 4,
                            Description = "Introductory physics and mechanics",
                            SubjectName = "Physics"
                        },
                        new
                        {
                            SubjectId = 3,
                            Credits = 2,
                            Description = "English communication and writing",
                            SubjectName = "English"
                        },
                        new
                        {
                            SubjectId = 4,
                            Credits = 3,
                            Description = "General chemistry and reactions",
                            SubjectName = "Chemistry"
                        });
                });

            modelBuilder.Entity("StudentLifeApp_BE.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("StudentCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CCAC75CB51E4");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "StudentCode" }, "UQ__Users__1FC886045B65753A")
                        .IsUnique()
                        .HasFilter("[StudentCode] IS NOT NULL");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105344FFD76AF")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 3, 4, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@lms.local",
                            FullName = "Admin User",
                            PasswordHash = "admin-placeholder-hash",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 3, 4, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "teacher1@lms.local",
                            FullName = "Teacher One",
                            PasswordHash = "teacher-placeholder-hash",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 3, 4, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student1@lms.local",
                            FullName = "Student One",
                            PasswordHash = "student-placeholder-hash",
                            RoleId = 3,
                            StudentCode = "S001"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2026, 3, 4, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student2@lms.local",
                            FullName = "Student Two",
                            PasswordHash = "student2-placeholder-hash",
                            RoleId = 3,
                            StudentCode = "S002"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2026, 3, 4, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student3@lms.local",
                            FullName = "Student Three",
                            PasswordHash = "student3-placeholder-hash",
                            RoleId = 3,
                            StudentCode = "S003"
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2026, 3, 4, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "student4@lms.local",
                            FullName = "Student Four",
                            PasswordHash = "student4-placeholder-hash",
                            RoleId = 3,
                            StudentCode = "S004"
                        });
                });

            modelBuilder.Entity("StudentLifeApp_BE.Models.Assignment", b =>
                {
                    b.HasOne("StudentLifeApp_BE.Models.User", "CreatedByNavigation")
                        .WithMany("Assignments")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Assignment_Teacher");

                    b.HasOne("StudentLifeApp_BE.Models.Subject", "Subject")
                        .WithMany("Assignments")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Assignment_Subject");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentLifeApp_BE.Models.Enrollment", b =>
                {
                    b.HasOne("StudentLifeApp_BE.Models.Subject", "Subject")
                        .WithMany("Enrollments")
                        .HasForeignKey("SubjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Enroll_Subject");

                    b.HasOne("StudentLifeApp_BE.Models.User", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Enroll_User");

                    b.Navigation("Subject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentLifeApp_BE.Models.News", b =>
                {
                    b.HasOne("StudentLifeApp_BE.Models.User", "CreatedByNavigation")
                        .WithMany("News")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_News_User");

                    b.HasOne("StudentLifeApp_BE.Models.Role", "TargetRole")
                        .WithMany("News")
                        .HasForeignKey("TargetRoleId")
                        .HasConstraintName("FK_News_Role");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("TargetRole");
                });

            modelBuilder.Entity("StudentLifeApp_BE.Models.Note", b =>
                {
                    b.HasOne("StudentLifeApp_BE.Models.User", "User")
                        .WithMany("Notes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notes_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StudentLifeApp_BE.Models.StudentAssignmentStatus", b =>
                {
                    b.HasOne("StudentLifeApp_BE.Models.Assignment", "Assignment")
                        .WithMany("StudentAssignmentStatuses")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Status_Assignment");

                    b.HasOne("StudentLifeApp_BE.Models.User", "Student")
                        .WithMany("StudentAssignmentStatuses")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Status_Student");

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentLifeApp_BE.Models.User", b =>
                {
                    b.HasOne("StudentLifeApp_BE.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("StudentLifeApp_BE.Models.Assignment", b =>
                {
                    b.Navigation("StudentAssignmentStatuses");
                });

            modelBuilder.Entity("StudentLifeApp_BE.Models.Role", b =>
                {
                    b.Navigation("News");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("StudentLifeApp_BE.Models.Subject", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("StudentLifeApp_BE.Models.User", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Enrollments");

                    b.Navigation("News");

                    b.Navigation("Notes");

                    b.Navigation("StudentAssignmentStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
